services:
  perm:
    build: perm
    container_name: "perm"
    ports:
      - "0.0.0.0:8000:5000"
    networks:
      web-internal:
          ipv4_address: 173.17.206.229
      internet:
          ipv4_address: 173.17.205.229
  selenium:
    image: selenium/standalone-chrome
    shm_size: '2gb'
    networks:
      web-internal:
          ipv4_address: 173.17.206.247
      internet:
          ipv4_address: 173.17.205.247
#    user: "1000:1000"


networks:
  internet:
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 173.17.205.0/24
          gateway: 173.17.205.1
          
  web-internal:
    internal: true
    ipam:
       config:
         - subnet:  173.17.206.1/24
